### ISSUE TITLE
[Node.js FastTrack] Assignment # 3 BloggerDemo - Ready for Review #1 #3

### ISSUE THREAD

**Issue by baddooz** [baddooz/nodejs#4]
/cc @codepathreview @codepath

due to an error on multipart parsing since last 24 hrs, couldnt complete complettly

blog submit page
1e 
 parsed req :  { blogname: [ 'sdasddasd' ],
  blogdescription: [ 'asdasda' ],
  mypost: [ '' ] }
Error: stream ended unexpectedly
    at Form.<anonymous> (/Users/bsubram/git/nodejs/blogger-demo/node_modules/multiparty/index.js:754:24)
    at emitNone (events.js:72:20)
    at Form.emit (events.js:166:7)
    at finishMaybe (_stream_writable.js:468:14)
    at endWritable (_stream_writable.js:478:3)
    at Form.Writable.end (_stream_writable.js:443:5)
    at onend (_stream_readable.js:490:10)
    at doNTCallback0 (node.js:407:9)
    at process._tickDomainCallback (node.js:377:13)

**Comment by codepathreview** [comment]
Based on the code currently pushed, you just need to update the form field name for the HTML file input:

``` node
// In routes.js
// Change this line...
app.use(multer({ dest: './uploads/'}).single('photo'))

// To this line (since the "name" of the "file" form field in blogpage.ejs is "image")...
app.use(multer({ dest: './uploads/'}).single('image'))
```

Please resubmit by commenting here once you've had a chance to complete the assignment.

/cc @CrabDude

EDIT: The first google search result for your error message is a [StackOverflow](http://stackoverflow.com/questions/31530200/node-multer-unexpected-field) that explains the issue a bit.

**Comment by baddooz** [comment]
/cc @CrabDude
resubmitted my demo app

**Comment by codepathreview** [comment]
:+1: nice work. The goal of this assignment was to learn how to implement local authentication, interact with a data store, and render a webUI. In addition, you explored using middleware to faciliate common HTTP functionality. Over the next few weeks, we'll be focusing on more complex integrations and realtime functionality that we find in modern APIs and web apps.

Here's a checklist of things that I'm looking for in this project. You should review the checklist, and make any changes to your project, if necessary.
- Review the properties and methods that you've made available through your various `module.exports`. Your modules should reveal the minimum interface and only expose things that must be used by other modules.
- There should be no `*Sync` calls anywhere in your code, and no `require` calls except at the top of each module file.
- All required dependencies should be declared in the package.json `"dependencies"`. When installing dependencies, use the `--save` option: `npm install --save somepackage`.
- Keep your code DRY by refactoring all code interacting with `req` or `res` into a reusable composable middleware: `(req, res, next)=>{}`.
- Your Models should exist each in their own module file, and Mongo embedded objects should have their own Schema. It is okay to include an embedded object's schema in the same file if it's not used in other schemas.
- Be sure to validate all user inputs. First, through strict enforcements in your data schemas, and second in your user, post and comment creation routes. Never rely solely on your schema for validation.
- All routes requiring a user account should enforce authentication through the `isLoggedIn` or equivalent route middleware: `app.post('/post/:postId', isLoggedIn, ...)`
- When handling user authentication data, security is paramount. Never store plain-text passwords anywhere, and always be sure to use at least a global salt (pepper) when hashing.
